version: '3.1'

services:
  srv_gin:
    build:
      context: .
      args:
        - SRC=${SRCDIR}
        - LOG=${LOGDIR}
        - RUN=${RUNDIR}
        - ETC=${ETCDIR}
        - BIN=${BINDIR}
        - APPNAME=${APPNAME}
        - REPODIR=${DIRREPO_CTN}
    ports:
      - 8082:8082
    volumes:
      - .:${SRCDIR}
      - ${DIRREPO_HOST}:${DIRREPO_CTN}
      - /root/.ssh:/root/.ssh
    environment:
      - FLOG=0
      - SILENT=0
      - GINMODE=DEBUG
      - REPO_NAME=${REPONAME}
      - REPO_DIR=${DIRREPO_CTN}
    container_name: ctn_gin
    stdin_open: true
    entrypoint: [ "${BINDIR}/${APPNAME}" ]
