version: '3.1'

services:
  srv_gin:
    build: 
      context: .
      args:
        - SRC=${SRCDIR}
        - LOG=${LOGDIR}
        - RUN=${RUNDIR}
        - ETC=${ETCDIR}
        - BIN=${BINDIR}
        - APPNAME=${APPNAME}
    ports:
      - 8082:8082 
    volumes:
      - .:${SRCDIR}
      - /var/autodeploy/repo:${DIRREPO_HOST}
    environment:
      - FLOG=0
      - SILENT=0
      - GINMODE=DEBUG
      - REPO_NAME=${REPONAME}
      - REPO_DIR=/var/autodeploy/repo
    container_name: ctn_gin
    stdin_open: true
    entrypoint: ["${BINDIR}/${APPNAME}"]
  