version: '3.1'

services:
  srv_gin:
    build:
      context: .
      args:
        - SRC=${SRCDIR}
        - LOG=${LOGDIR}
        - RUN=${RUNDIR}
        - ETC=${ETCDIR}
        - BIN=${BINDIR}
        - APPNAME=${APPNAME}
        - REPODIR=${DIRREPO_CTN}
    ports:
      - 8082:8082
    volumes:
      - .:${SRCDIR}
      - ${DIRREPO_HOST}:${DIRREPO_CTN} # repo that needs updation is mounted on the container
      - /root/.ssh:/root/.ssh # when running git repo, ssh key of the host percolate to ctn
    environment:
      - FLOG=0
      - SILENT=0
      - GINMODE=DEBUG
      - REPO_NAME=${REPONAME}
      - REPO_DIR=${DIRREPO_CTN}
    container_name: ctn_gin
    # relation with the host 
    # We want commands to run on the host but from within the container
    stdin_open: true
    tty: true
    privileged: true
    pid: "host"
    # How does the container start
    entrypoint: [ "${BINDIR}/${APPNAME}" ]
